drigan/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.conf.urls.static import static
from django.contrib import admin
from drigan.views import StartView
# Uncomment the next two lines to enable the admin:

admin.autodiscover()

import events.urls, dynamic_forms.urls, run_manager.urls, run_ranking.urls

urlpatterns = patterns('',
    url(r'^$', StartView.as_view(), name="index"),
    url(r'^events/', include('events.urls',)),

    url(r'^forms/', include(events.urls.dynform_url_overrides + dynamic_forms.urls.urlpatterns)),

    url(r'^run/', include('run_manager.urls')),
    url(r'^ranking/', include('run_ranking.urls')),
    # Examples:
    # url(r'^$', 'drigan.views.home', name='home'),
    # url(r'^drigan/', include('drigan.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),


    url(r'^accounts/', include('drigan_registration.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/models.py
# -*- coding: utf-8 -*-
import datetime

from django.core.urlresolvers import reverse
from django.conf import settings
from django.db import models, transaction
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import ugettext_lazy as _

from guardian.shortcuts import assign_perm, get_users_with_perms

from dynamic_forms.models import DynamicForm
from dynamic_forms.list_visibility_restrictions import \
    default_access_participants_list_restrictions
import os.path

from reversion import revisions as reversion

LIST_VISIBLE_FOR_ORGANIZER = "organizer"


def get_datetime_help_text():
    format = settings.DATETIME_INPUT_FORMATS[0]
    totally_random_date = datetime.datetime(1985, 9, 19, 21, 30)
    message = _("""Please provide date and time according to the following example {example}. You may omit the time part.""").strip().format(
        format=format,
        example=totally_random_date.strftime(format))
    return message


def visible_for_organizer(user, form):
    """
    Restriction for DynamicForm's Participants List making it visible only for
    event organizer.
    """
    if user.is_authenticated():
        if (form.list_visibility == LIST_VISIBLE_FOR_ORGANIZER or
            form.list_visibility == DynamicForm.LIST_VISIBLE_FOR_PARTICIPANTS) and\
                form.content_object.event.organizer.related_user == user:
            return True
    return False


def visible_for_everyone_who_can_edit(user, form):
    return Attraction.DynamicFormMeta.can_edit(user, form)


class Category(models.Model):
    class Meta:
        verbose_name_plural = _('attraction categories')

    name = models.CharField(max_length=100, verbose_name=_('name'))
    slug = models.SlugField(verbose_name=_('slug'))
    attraction_only = models.BooleanField(default=False)

    def __str__(self):
        return self.name


@reversion.register()
class Organizer(models.Model):
    class Meta:
        verbose_name = _('organizer')
        verbose_name_plural = _('organizers')

    name = models.CharField(_("name"), max_length=200)
    mail = models.EmailField(_("e-mail address"))
    phone = models.CharField(_("phone number"), max_length=20)
    address = models.TextField(_("address"), blank=True, null=True)
    related_user = models.ForeignKey(User, null=False, blank=False)

    def __unicode__(self):
        return self.name


class SerialEventGroup(models.Model):
    name = models.CharField(_("name"), max_length=200)

    def __unicode__(self):
        return self.name


@reversion.register()
class Event(models.Model):

    class Meta:
        verbose_name = _('event')
        verbose_name_plural = _('events')

    name = models.CharField(_("event name"), max_length=200,
                            help_text=_("Without edition (eg. \"Long Race\", "
                                        "not \"Long Race 2013\")"))

    start_date = models.DateTimeField(
        _("start date of the event"),
        null=True, blank=True,
        help_text=get_datetime_help_text())

    end_date = models.DateTimeField(
        _("end date of the event"),
        null=True, blank=True,
        help_text=get_datetime_help_text())

    logo = models.ImageField(upload_to='uploads/events/logos',
                             null=True, blank=True)

    website = models.URLField(_("website"), max_length=100, blank=True)

    # TODO: Rename to owner
    created_by = models.ForeignKey(User, related_name="events")
    category = models.ForeignKey(Category,
                                 verbose_name=_('category'))
    description = models.TextField(_("description of the event"),
                                   blank=True, null=True)
    organizer = models.ForeignKey(Organizer)
    edition = models.CharField(_("edition name"), max_length=100,
                               blank=True,
                               help_text=_("Only if event is cyclic (eg. "
                                           "\"1\", \"2014\")"))
    event_group = models.ForeignKey(SerialEventGroup, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_logo(self):

        if self.logo:
            try:
                self.logo.open('rb')
            except:
                return None
            return self.logo
        else:
            return None

    def get_other_editions(self):
        if self.event_group:
            return self.event_group.event_set.all().exclude(
                edition=self.edition)

    def get_absolute_url(self):
        return reverse("events-event-details", args=(self.id,))

    @transaction.atomic()
    def save(self, raw=False, **kwargs):

        # TODO: To anyone wandering: this is a hack and a workaround.
        # If we change created_by user new user is assigned edition rights
        # while owner still retains these rights.
        # Probably this needs more thought but it works.

        # TODO: This relies on undocumented? behavious of passing raw to
        # save method.

        if raw:
            super().save(raw=raw, **kwargs)
            return

        with transaction.atomic():
            is_creating = self.pk is None
            old_user = None
            if not is_creating:
                try:
                    old_user = Event.objects\
                        .only("created_by").get(pk=self.pk).created_by
                except Event.DoesNotExist:
                    pass
                    # TODO: Happens during undelete, should patch sofdtelete to
                    # So it passes raw=True to save.
            super().save(**kwargs)

            if old_user != self.created_by:
                assign_perm('events.change_event', self.created_by, self)
                assign_perm('events.delete_event', self.created_by, self)

            for a in self.attractions.all():
                assign_perm('events.change_attraction', self.created_by, a)
                assign_perm('events.delete_attraction', self.created_by, a)

    def get_admins(self):
        return list(get_users_with_perms(self))

    @staticmethod
    def get_all_admins():
        users = []
        for event in Event.objects.all():
            templist = list(get_users_with_perms(event))
            users = list(set(users) | set(templist))
        return users


@reversion.register()
class Attraction(models.Model):

    event = models.ForeignKey(Event, related_name="attractions")
    name = models.CharField(_("name"), max_length=200)
    start_date = models.DateTimeField(
        _("start date"), help_text=get_datetime_help_text())
    end_date = models.DateTimeField(
        _("end date"), help_text=get_datetime_help_text())
    logo = models.ImageField(upload_to='uploads/events/logos',
                             null=True, blank=True)
    place = models.CharField(_("place"), max_length=200)
    description = models.TextField(
        _("description of the attraction"), null=True, blank=True)
    category = models.ForeignKey(Category,
                                 verbose_name=_('category'))
    registered_only = models.BooleanField(_("Registered users only"), default=False)
    confirm_registration = models.BooleanField(_("Confirm user registration"), default=False)

    def __str__(self):
        return self.name

    def get_logo(self):
        if self.logo:
            return self.logo
        else:
            return None

    @property
    def forms(self):
        """ Returns a list off all forms related to this attraction """
        content_type = ContentType.objects.get_for_model(self)
        forms = DynamicForm.objects.filter(object_id=self.id,
                                           content_type=content_type)
        return forms

    def get_absolute_url(self):
        return reverse("events-attraction-details", args=(self.id,))

    def save(self, **kwargs):
        with transaction.atomic():
            super().save(**kwargs)
            assign_perm('events.change_attraction', self.event.created_by, self)
            assign_perm('events.delete_attraction', self.event.created_by, self)

    def get_admins(self):
        return list(get_users_with_perms(self))

    @staticmethod
    def get_all_admins():
        users = []
        for attraction in Attraction.objects.all():
            templist = list(get_users_with_perms(attraction))
            users = list(set(users) | set(templist))
        return users

    class Meta:
        ordering = ['start_date', 'name']
        verbose_name = _('attraction')
        verbose_name_plural = _('attractions')

    class DynamicFormMeta:

        @staticmethod
        def can_edit(user, form):
            return user.has_perm("change_attraction", form.content_object)

        list_visibility_choices = (
            (DynamicForm.LIST_VISIBLE_FOR_ALL, _("everyone")),
            (LIST_VISIBLE_FOR_ORGANIZER, _("organizer only")),
            (DynamicForm.LIST_VISIBLE_FOR_PARTICIPANTS, _("all participants")),
        )

        access_participants_list_restrictions = \
            default_access_participants_list_restrictions + \
            [visible_for_organizer, visible_for_everyone_who_can_edit]

        default_list_visibility = LIST_VISIBLE_FOR_ORGANIZER

        @staticmethod
        def can_save(user, form):
            if user == form.content_object.event.organizer.related_user:
                return True
            return False

drigan/forms.py
from django.forms import Form, ModelForm


class DriganForm(Form):
    error_css_class = "form-error"
    required_css_class = 'form-required'


class DriganModelForm(ModelForm):
    error_css_class = "form-error"
    required_css_class = 'form-required'

drigan/views.py
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone
from django.views.generic.list import ListView
from events.models import Event
from guardian.shortcuts import get_objects_for_user

from datetime import datetime


class StartView(ListView):

    template_name = "start.html"
    context_object_name = 'upcoming_events_list'
    def get_queryset(self):
        all_events = Event.objects.order_by('-start_date').filter(start_date__gt=datetime.now())
        return all_events

    def get_context_data(self, *args, **kwargs):
        context = super(StartView, self).get_context_data(*args, **kwargs)
        user = self.request.user
        if user.is_authenticated():
            my_events = get_objects_for_user(user, 'events.change_event', None, True, False, False) | user.events.all()
            my_events = my_events.order_by('-start_date')
            context['user_events_list'] = my_events
        return context

drigan/templates/base.html
{% load i18n staticfiles %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="utf-8">
    <meta name="description" content="timing.czteryporysportu.pl">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% if flatpage %}{{ flatpage.title }}{% endif %}{% endblock %} | timing.czteryporysportu.pl</title>

    <script src="{% static "jquery-1.11.1.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.min.js" %}"></script>
    <script src="{% static "scripts.js" %}"></script>

    <link href="{% static "style.css" %}" rel="stylesheet">
    {% block head %}{% endblock %}
</head>
<body>
  <div id="wrapper">
    <header class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">CPS Timing</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% if user.is_staff %}
                <li class="active"><a href="{% url 'admin:index' %}">{% trans "Admin" %}</a></li>
            {% endif %}
            {% if perms.events.add_event or DRIGAN_CREATE_EVENTS_WITHOUT_PERMISSION %}
                <li><a href="/events/add">{% trans "Add event" %}</a></li>
            {% endif %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
	        {% if user.is_authenticated %}
              <li><a href="">{{ user }}</a></li>
              <li><a href="{% url "auth_logout" %}?next={{ request.path }}">{% trans "Sign out" %}!</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </header>
    <div class="content container">
      {% if messages %}
      <div class="messages">
        {% for message in messages %}
        <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
      </div>
      {% endif %}
      {% block content %}{% endblock %}
    </div><!-- /.container -->
  </div><!-- /#wrapper -->
  <footer class="container">
      Elektroniczny pomiar czasu wykonany przez <a href="http://czteryporysportu.pl">Cztery Pory Sportu</a> 
      -- prawdopodobnie najbardziej sportowe miejsce w Jeleniej Górze.
  </footer>
</body>
</html>

drigan/templates/base_presentation.html
{% load i18n staticfiles %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="utf-8">
    <meta name="description" content="Drigan field control">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% if flatpage %}{{ flatpage.title }}{% endif %}{% endblock %} | presentation</title>

    <link href="{% static "style-presentation.css" %}" rel="stylesheet">
    {% block head %}{% endblock %}
</head>
<body>
  {% block content %}{% endblock %}
  <script src="{% static "vendor/js/jquery-1.10.2.min.js" %}"></script>
  <script src="{% static "vendor/bootstrap/js/bootstrap.min.js" %}"></script>
  <script src="{% static "scripts.min.js" %}"></script>
</body>
</html>

drigan/templates/start.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Upcoming events" %}{% endblock %}

{% block content %}
{% if perms.events.add_event or DRIGAN_CREATE_EVENTS_WITHOUT_PERMISSION %}
    <a href="{% url "events.views.add_event" %}" class='add-event-button'>{% trans "Organize your event with us!" %}</a>
{% endif %}
{% if user.is_authenticated %}
    <h2>{% trans "My events" %}:</h2>
    {% include "events/partials/event_list.html" with events=user_events_list %}
{% endif %}
<h2>{% trans "Upcoming events" %}:</h2>
{% include "events/partials/event_list.html" with events=upcoming_events_list %}
{% endblock %}